[package]
name = "routinator"
version = "0.1.0"
authors = ["The NLnet Labs RPKI Team <rpki@nlnetlabs.nl>"]

[dependencies]
rpki            = { git="https://github.com/NLnetLabs/rpki-rs.git" }
bytes           = "^0.4"
chrono          = "^0.4"
clap            = "2.0"
daemonize	= "^0.3"
env_logger      = "^0.5"
failure         = "^0.1"
futures         = "^0.1"
futures-cpupool = "^0.1"
json		= "^0.11"
lazy_static     = "1.1"
log             = "^0.4"
num_cpus        = "1.0"
slab            = "^0.4"
tokio           = "^0.1"
tokio-process   = "^0.2"

